routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\mainController;
use App\Http\Controllers\adminController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  FrontEnd
Route::get('/home',[mainController::class,'index'])->name('home');
Route::get('/tour',[mainController::class,'tour'])->name('tour');
Route::get('/tour-detail/{id}',[mainController::class,'tourDetail'])->name('tourDetail');
Route::get('/about',[mainController::class,'about'])->name('about');
Route::get('/contact',[mainController::class,'contact'])->name('contact');
Route::post('/client-add',[mainController::class,'clientAdd'])->name('clientAdd');
//  Backend
Route::group(['prefix'=>'admin','as'=>'admin.'] ,function() {
    Route::get('/dashboard',[adminController::class,'index'])->name('dashboard');
    Route::get('/tour-create',[adminController::class,'tourCreate'])->name('tourCreate');
    Route::post('/tour-save',[adminController::class,'tourSave'])->name('tourSave');
    Route::get('/tour-edit/{id}',[adminController::class,'tourEdit'])->name('tourEdit');
    Route::post('/tour-update',[adminController::class,'tourUpdate'])->name('tourUpdate');
    Route::get('/tour-clone/{id}',[adminController::class,'tourClone'])->name('tourClone');
    Route::get('/tour-view',[adminController::class,'tourView'])->name('tourView');
    Route::get('/tour-clients/{id}',[adminController::class,'tourClients'])->name('tourClients');
    Route::get('/tour-individual-view/{id}',[adminController::class,'tourInView'])->name('tourInView');
    Route::get('/member-view',[adminController::class,'memberView'])->name('memberView');
    Route::get('/member-edit/{id}',[adminController::class,'clientEdit'])->name('memberEdit');
    Route::post('/member-update',[adminController::class,'clientUpdate'])->name('memberUpdate');
    Route::post('/member-save',[adminController::class,'clientSave'])->name('memberSave');
    Route::post('/profile',[adminController::class,'profile'])->name('profile');
    Route::get('profile', function () {
        return view('backend.profile');
    })->name('profile');
});
Route::get('logout',function(){
    Auth::logout(); 
    return redirect('/home');
});
Route::get('/',function(){
    return redirect('/home');
});
Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/backend/memberView.blade.php
@extends('app')
@section('content')
        <!-- Page Wrapper -->
        <div class="page-wrapper">

            <!-- Page Content -->
            <div class="content container-fluid">

                <!-- Page Header -->
                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item active">View Customers</li>
                            </ul>
                        </div>
                        <div class="col-auto float-right ml-auto mb-4">
                            <a href="#" class="btn add-btn" data-toggle="modal" data-target="#create_project"><i
                                    class="fa fa-plus"></i> Create Customer</a>
                            <div class="view-icons">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Page Header -->

                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped custom-table mb-0 datatable">
                                <thead>
                                    <tr>
                                        <th>Customer Name </th>
                                        <th>Phone Number</th>
                                        <th>Payment Status</th>
                                        <th>Tour Name</th>
                                        {{-- <th>Status</th> --}}
                                        <th>No of Persons</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                             @foreach($clients as $client)
                                    <tr>
                                        <td>{{ $client->name }}</td>
                                        <td>{{ $client->phone }}</td>
                                        <td>{{ $client->payment }}</td>
                                        <td>{{ $client->tour->title }}</td>
                                        {{-- <td>
                                            <span class="badge bg-inverse-danger">Half Payment</span>
                                        </td> --}}
                                        <td>
                                           {{count($client->persons()->get())}}
                                        </td>
                                       
                                        <td>
                                            <a href="{{ route('admin.memberEdit',$client->id) }}" data-toggle="tooltip" data-placement="top"
                                                title="Edit" class="bell-icon" data-original-title="Edit">
                                                <i class="fas fa-pencil fa-lg"></i>
                                            </a>
                                            <a href="{{ route('admin.tourInView',$client->id) }}" data-toggle="tooltip" data-placement="top" title="View"
                                                class="bell-icon ml-1" data-original-title="View">
                                                <i class="fa fa-eye fa-lg"></i>
                                            </a>

                                        </td>
                                    </tr>  
                             @endforeach
                                    
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /Page Content -->

            <div id="create_project" class="modal custom-modal fade" role="dialog">
                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Create Customer</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{{ route('admin.memberSave') }}">
                                @csrf
                                {{--  <input type="hidden" value="{{ $id->id }}" name="tour_id">  --}}
                                    <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Full Name</label>
                                            <input class="form-control" type="text" name="name" value="">
                                        </div>
                                    </div>
                                     <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>CNIC</label>
                                            <input class="form-control" name="cnic" value="" type="text">
                                        </div>
                                    </div>
                                </div>
                                
                               
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Mobile Number</label>
                                            <input placeholder="" name="phone" value="" class="form-control" type="tel">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input placeholder="" name="email" value="" class="form-control" type="email">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                   
                                   <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Payment</label>
                                            <input class="form-control" type="text" name="payment" value="">
                                        </div>
                                   </div>
                                   <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Select Tour</label>
                                            <select name="tour_id" id="">
                                                @foreach($id as $tour)
                                                <option value="{{ $tour->id }}">{{ $tour->title }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                   </div>
                                </div>
                               
                                <div class="submit-section">
                                    <button class="btn btn-primary submit-btn">Submit</button>
                                </div>
                    </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /Page Wrapper -->
@endsection

resources/views/backend/tourClient.blade.php
@extends('app')
@section('content')
        <!-- Page Wrapper -->
        <div class="page-wrapper">

            <!-- Page Content -->
            <div class="content container-fluid">

                <!-- Page Header -->
                <div class="page-header">
                    <div class="row">
                        <div class="col-sm-12">
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item active">View Customers</li>
                            </ul>
                        </div>
                        <div class="col-auto float-right ml-auto mb-4">
                            <a href="#" class="btn add-btn" data-toggle="modal" data-target="#create_project"><i
                                    class="fa fa-plus"></i> Create Customer</a>
                            <div class="view-icons">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Page Header -->

                <div class="row">
                    <div class="col-md-12">
                        <div class="table-responsive">
                            <table class="table table-striped custom-table mb-0 datatable">
                                <thead>
                                    <tr>
                                        <th>Sr#</th>
                                        <th>Customer Name </th>
                                        <th>Phone Number</th>
                                        <th>Payment Status</th>
                                        <th>Tour Name</th>
                                        {{-- <th>Status</th> --}}
                                        <th>No of Persons</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>

                             @foreach($clients as $client)
                                    <tr>
                                        <td>{{ $loop->index+1 }}</td>
                                        <td>{{ $client->name }}</td>
                                        <td>{{ $client->phone }}</td>
                                        <td>{{ $client->payment }}</td>
                                        <td>{{ $client->tour->title }}</td>
                                        {{-- <td>
                                            <span class="badge bg-inverse-danger">Half Payment</span>
                                        </td> --}}
                                        <td>
                                             {{  isset($client->parent) ? " with ".$client->parent['name'] : count($client->persons()->get()) }}
                                        </td>
                                       
                                        <td>
                                            <a href="{{ route('admin.memberEdit',$client->id) }}" data-toggle="tooltip" data-placement="top"
                                                title="Edit" class="bell-icon" data-original-title="Edit">
                                                <i class="fas fa-pencil fa-lg"></i>
                                            </a>
                                            <a href="{{ route('admin.tourInView',$client->id) }}" data-toggle="tooltip" data-placement="top" title="View"
                                                class="bell-icon ml-1" data-original-title="View">
                                                <i class="fa fa-eye fa-lg"></i>
                                            </a>

                                        </td>
                                    </tr>  
                             @endforeach
                                    
                                   
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

            </div>
            <!-- /Page Content -->

            <div id="create_project" class="modal custom-modal fade" role="dialog">
                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Create Customer</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form method="POST" action="{{ route('admin.memberSave') }}">
                                @csrf
                                <input type="hidden" value="{{ $id->id }}" name="tour_id">
                                    <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Full Name</label>
                                            <input class="form-control" type="text" name="name" value="">
                                        </div>
                                    </div>
                                     <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>CNIC</label>
                                            <input class="form-control" name="cnic" value="" type="text">
                                        </div>
                                    </div>
                                </div>
                                
                               
                                <div class="row">
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Mobile Number</label>
                                            <input placeholder="" name="phone" value="" class="form-control" type="tel">
                                        </div>
                                    </div>
                                    <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input placeholder="" name="email" value="" class="form-control" type="email">
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                   
                                   <div class="col-sm-6">
                                        <div class="form-group">
                                            <label>Payment</label>
                                            <input class="form-control" type="text" name="payment" value="">
                                        </div>
                                   </div>
                                </div>
                               
                                <div class="submit-section">
                                    <button class="btn btn-primary submit-btn">Submit</button>
                                </div>
                    </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <!-- /Page Wrapper -->
@endsection

resources/views/backend/tourInView.blade.php
@extends('app')
@section('content')
           <!-- Page Wrapper -->
           <div class="page-wrapper">

            <!-- Page Content -->
            <div class="content container-fluid">

                <!-- Page Header -->
                <div class="page-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h3 class="page-title">Customers</h3>

                        </div>
                        <div class="col-auto float-right ml-auto mb-4">
                            <a href="#" class="btn add-btn" data-toggle="modal" data-target="#create_project"><i
                                    class="fa fa-plus"></i> Create Customer</a>
                            <div class="view-icons">
                            </div>
                        </div>
                    </div>
                    <!-- /Page Header -->

                    <!-- Search Filter -->
                    {{--  <div class="row filter-row">
                        <div class="col-sm-6 col-md-4">
                            <div class="form-group form-focus">
                                <input type="text" class="form-control floating">
                                <label class="focus-label">Tour Title</label>
                            </div>
                        </div>

                        <div class="col-sm-6 col-md-4">
                            <div class="form-group form-focus select-focus">
                                <select class="select floating">
                                    <option>Half Payment</option>
                                    <option>Full Payment</option>
                                </select>
                                <label class="focus-label">Payment</label>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-4">
                            <a href="#" class="btn btn-success btn-block"> Search </a>
                        </div>
                    </div>  --}}
                    <!-- Search Filter -->

                    <div class="row">

                    @foreach($data->persons as $client)
                        <div class="col-md-4 d-flex">
                            <div class="card profile-box flex-fill">
                                <div class="card-body">
                                    <h3 class="card-title">Customer Information
                                        <a href="{{ route('admin.memberEdit',$client->id) }}" target="_blank" class="edit-icon"><i class="fa fa-pencil"></i></a>
                                    </h3>
                                    <ul class="personal-info">
                                        <li>
                                            <div class="title">Full Name.</div>
                                            <div class="text" >{{ $client->name }}</div>
                                        </li>
                                        <li>
                                            <div class="title">CNIC.</div>
                                            <div class="text" >{{ $client->cnic }}</div>
                                        </li>
                                        <li>
                                            <div class="title">Tel</div>
                                            <div class="text" ><a href="">{{ $client->phone }}</a></div>
                                        </li>
                                        <li>
                                            <div class="title">Email</div>
                                            <div class="text" >{{ $client->email }}</div>
                                        </li>
                                        
                                        <li>
                                            <div class="title">Payment Status</div>
                                            <div class="text" >RS {{ $client->payment }}</div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                         </div>
                        @endforeach
                        
                    </div>

                </div>
                <!-- /Page Content -->
                <!-- Create Project Modal -->
                <div id="create_project" class="modal custom-modal fade" role="dialog">
                    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Create Customer</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <form method="POST" action="{{ route('admin.memberSave') }}">
                                    @csrf
                                    <input type="hidden" value="{{ $data->tour->id }}" name="tour_id">
                                    <input type="hidden" value="{{ $data->id }}" name="parent_id">
                                        <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>Full Name</label>
                                                <input class="form-control" type="text" name="name" value="">
                                            </div>
                                        </div>
                                         <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>CNIC</label>
                                                <input class="form-control" name="cnic" value="" type="text">
                                            </div>
                                        </div>
                                    </div>
                                    
                                   
                                    <div class="row">
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>Mobile Number</label>
                                                <input placeholder="" name="phone" value="" class="form-control" type="tel">
                                            </div>
                                        </div>
                                        <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>Email</label>
                                                <input placeholder="" name="email" value="" class="form-control" type="email">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                       
                                       <div class="col-sm-6">
                                            <div class="form-group">
                                                <label>Payment</label>
                                                <input class="form-control" type="text" name="payment" value="">
                                            </div>
                                       </div>
                                    </div>
                                   
                                    <div class="submit-section">
                                        <button class="btn btn-primary submit-btn">Submit</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /Create Project Modal -->
            </div>
            <!-- /Page Wrapper -->

        </div>
        <!-- /Main Wrapper -->

@endsection

resources/views/backend/tourView.blade.php
@extends('app')
@section('content')
    <!-- Page Wrapper -->
    <div class="page-wrapper">

        <!-- Page Content -->
        <div class="content container-fluid">

            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item active">View Tours</li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->

            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table table-striped custom-table mb-0 datatable">
                            <thead>
                            <tr>
                                <th>Sr#</th>
                                <th>Title </th>
                                <th>Days</th>
                                <th>Destination</th>
                                <th>Departure Time</th>
                                <th>Total Persons</th>
                                <th>Image</th>
                                <th>Price</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                        @foreach($records as $data)
                            
                            <tr>
                                <td>{{ $loop->index+1 }}</td>
                                <td>{{ $data->title }}</td>
                                <td>{{ $data->days }}</td>
                                <td>{{ $data->destination }}</td>
                                <td>{{ $data->departureTime }}</td>
                                <td>{{ count($data->clients()->get()) }}</td>
                                {{-- <td>
                                    <span class="badge bg-inverse-danger">Close</span>
                                </td>--}}
                                <td>
                                    <img src="{{ asset('frontend/') }}/assets/img/{{ $data->photo }}" style="width: 80px" alt="">
                                </td> 
                                <td>RS {{ $data->price }}</td>
                                <td>
                                    <a href="{{route('admin.tourEdit',$data->id)}}" data-toggle="tooltip" data-placement="top"
                                       title="Edit" class="bell-icon" data-original-title="Edit">
                                        <i class="fas fa-pencil fa-lg"></i>
                                    </a>
                                    <a href="{{route('admin.tourClients',$data->id)}}" data-toggle="tooltip" data-placement="top" title="View"
                                       class="bell-icon ml-1" data-original-title="View">
                                        <i class="fa fa-eye fa-lg"></i>
                                    </a>

                                    <a href="{{route('admin.tourClone',$data->id)}}" data-toggle="tooltip" data-placement="top" title="Clone"
                                       class="bell-icon ml-1" data-original-title="Clone">
                                        <i class="far fa-clone fa-lg"></i>
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
        <!-- /Page Content -->

    </div>
    <!-- /Page Wrapper -->
@endsection