routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\mainController;
use App\Http\Controllers\adminController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//  FrontEnd
Route::get('/home',[mainController::class,'index'])->name('home');
Route::get('/tour',[mainController::class,'tour'])->name('tour');
Route::get('/tour-detail/{id}',[mainController::class,'tourDetail'])->name('tourDetail');
Route::get('/about',[mainController::class,'about'])->name('about');
Route::get('/contact',[mainController::class,'contact'])->name('contact');
Route::post('/client-add',[mainController::class,'clientAdd'])->name('clientAdd');
//  Backend
Route::group(['prefix'=>'admin','as'=>'admin.'] ,function() {
    Route::get('/dashboard',[adminController::class,'index'])->name('dashboard');
    Route::get('/tour-create',[adminController::class,'tourCreate'])->name('tourCreate');
    Route::post('/tour-save',[adminController::class,'tourSave'])->name('tourSave');
    Route::get('/tour-edit/{id}',[adminController::class,'tourEdit'])->name('tourEdit');
    Route::post('/tour-update',[adminController::class,'tourUpdate'])->name('tourUpdate');
    Route::get('/tour-clone/{id}',[adminController::class,'tourClone'])->name('tourClone');
    Route::get('/tour-view',[adminController::class,'tourView'])->name('tourView');
    Route::get('/tour-clients/{id}',[adminController::class,'tourClients'])->name('tourClients');
    Route::get('/tour-individual-view/{id}',[adminController::class,'tourInView'])->name('tourInView');
    Route::get('/member-view',[adminController::class,'memberView'])->name('memberView');
    Route::get('/member-edit/{id}',[adminController::class,'clientEdit'])->name('memberEdit');
    Route::post('/member-update',[adminController::class,'clientUpdate'])->name('memberUpdate');
    Route::post('/member-save',[adminController::class,'clientSave'])->name('memberSave');
    Route::post('/profile',[adminController::class,'profile'])->name('profile');
    Route::get('profile', function () {
        return view('backend.profile');
    })->name('profile');
});
Route::get('logout',function(){
    Auth::logout(); 
    return redirect('/home');
});
Route::get('/',function(){
    return redirect('/home');
});
Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/backend/layouts/aside.blade.php
<!-- Sidebar -->
<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li>
                    <a href="index.html" class="logo d-flex justify-content-center">
                        <img src="{{asset('backend')}}/assets/img/logo.png" width="100" height="auto" alt="">
                    </a>
                </li>
                <li>
                    <a href="{{route('admin.dashboard')}}"><i class="fas fa-tachometer-alt" style="font-size: 18px;"></i> <span> Dashboard</span></a>
                </li>

                <li class="submenu">
                    <a href="#"><i class="fas fa-mountain fa-sm" style="font-size: 18px;"></i> <span> Tours </span> <span
                                class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li><a href="{{route('admin.tourCreate')}}"> Create </a></li>
                        <li><a href="{{route('admin.tourView')}}"> View </a></li>
                    </ul>
                </li>
                <li class="submenu">
                    <a href="#"><i class="fas fa-user-friends" style="font-size: 18px;"></i> <span> Memebers </span> <span
                                class="menu-arrow"></span></a>
                    <ul style="display: none;">
                        <li><a href="{{route('admin.memberView')}}">View </a></li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</div>
<!-- /Sidebar -->

resources/views/backend/layouts/footer.blade.php
</div>
<!-- /Main Wrapper -->

<!-- jQuery -->
<script src="{{asset('backend')}}/assets/js/jquery-3.2.1.min.js"></script>

<!-- Bootstrap Core JS -->
<script src="{{asset('backend')}}/assets/js/popper.min.js"></script>
<script src="{{asset('backend')}}/assets/js/bootstrap.min.js"></script>

<!-- Slimscroll JS -->
<script src="{{asset('backend')}}/assets/js/jquery.slimscroll.min.js"></script>

<!-- Select2 JS -->
<script src="{{asset('backend')}}/assets/js/select2.min.js"></script>

<!-- Datetimepicker JS -->
<script src="{{asset('backend')}}/assets/js/moment.min.js"></script>
<script src="{{asset('backend')}}/assets/js/bootstrap-datetimepicker.min.js"></script>

<!-- Form Validation JS -->
<script src="{{asset('backend')}}/assets/js/form-validation.js"></script>

<!-- Custom JS -->
<script src="{{asset('backend')}}/assets/js/app.js"></script>

<!-- Datatable JS -->
<script src="{{asset('backend')}}/assets/js/jquery.dataTables.min.js"></script>
<script src="{{asset('backend')}}/assets/js/dataTables.bootstrap4.min.js"></script>

{{--  <script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>  --}}
<!-- Summernote JS -->
<script src="{{asset('backend')}}/assets/plugins/summernote/dist/summernote-bs4.min.js"></script>

<!-- Select2 -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

<script>
    $('.js-example-basic-single').select2();
</script>

  <!-- Select2 -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>
  <script src="{{asset('backend')}}/assets/js/multiselect.js"></script>
  <script src="{{asset('backend')}}/assets/js/myjs.js"></script>


  <script>
      $('.js-example-basic-single').select2();
  </script>
  <script>
      $(document).ready(function () {

          $("#file-upload-demo").fileinput({
              'theme': 'explorer',
              'uploadUrl': '#',
              overwriteInitial: false,
              initialPreviewAsData: true,
              initialPreview: [
                  "{{asset('backend')}}/assets/img/profiles/avatar-02.jpg",

              ],
              initialPreviewConfig: [{
                      caption: "{{asset('backend')}}/assets/img/img-01.jpg",
                      size: 329892,
                      width: "100",
                      url: "{{ route('admin.tourSave') }}",
                      key: 1,
                    //   data:{'_token':'{{ csrf_token() }}' }
                  },

              ]
          });

      });
  </script>


</body>

</html>

resources/views/backend/layouts/head.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description" content="Smarthr - Bootstrap Admin Template">
    <meta name="keywords"
          content="admin, estimates, bootstrap, business, corporate, creative, management, minimal, modern, accounts, invoice, html5, responsive, CRM, Projects">
    <meta name="author" content="Dreamguys - Bootstrap Admin Template">
    <meta name="robots" content="noindex, nofollow">
    <title>Dashboard</title>

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{{asset('backend')}}/assets/img/favicon.png">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/bootstrap.min.css">

    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/font-awesome.min.css">
    <!-- Datatable CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/dataTables.bootstrap4.min.css">

    <!-- Select2 CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/select2.min.css">

    <!-- Datetimepicker CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/bootstrap-datetimepicker.min.css">

    <!-- Lineawesome CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/line-awesome.min.css">

    <!-- Main CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/css/style.css">

    <!-- Summernote CSS -->
    <link rel="stylesheet" href="{{asset('backend')}}/assets/plugins/summernote/dist/summernote-bs4.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

          
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.7/css/fileinput.css" media="all"
    rel="stylesheet" type="text/css" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="{{asset('backend')}}/assets/js/html5shiv.min.js"></script>
    <script src="{{asset('backend')}}/assets/js/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- Main Wrapper -->
<div class="main-wrapper">

    <!-- Header -->
    <div class="header">

        <a id="toggle_btn" href="javascript:void(0);">
				<span class="bar-icon">
					<span></span>
					<span></span>
					<span></span>
				</span>
        </a>

        <!-- Header Title -->
        <div class="page-title-box">
            <h3>Tripwaalay</h3>
        </div>
        <!-- /Header Title -->

        <a id="mobile_btn" class="mobile_btn" href="#sidebar"><i class="fa fa-bars"></i></a>

        <!-- Header Menu -->
        <ul class="nav user-menu">

            <li class="nav-item dropdown has-arrow main-drop">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
						<span class="user-img"><img src="{{asset('backend')}}/assets/img/profiles/avatar-21.jpg" alt="">
							<span class="status online"></span></span>
                    <span>{{ auth::user()->name }}</span>
                </a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{{ route('admin.profile') }}">My Profile</a>
                    {{-- <a class="dropdown-item" href="settings.html">Settings</a> --}}
                    <a class="dropdown-item" href="{{ route('logout') }}">Logout</a>
                </div>
            </li>
        </ul>
        <!-- /Header Menu -->

        <!-- Mobile Menu -->
        <div class="dropdown mobile-user-menu">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i
                        class="fa fa-ellipsis-v"></i></a>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="profile.html">My Profile</a>
                <a class="dropdown-item" href="settings.html">Settings</a>
                <a class="dropdown-item" href="login.html">Logout</a>
            </div>
        </div>
        <!-- /Mobile Menu -->

    </div>
    <!-- /Header -->